First Try at GANs
bddmodelcar/training pull request #19
Opened 2017-07-22 20:06 UTC by BaladityaY

Cleaned up gradient_ascent.py and implemented GAN training based off pretrained squeezenet in gan_gradient_ascent.py

2017-07-22 20:12 UTC, tpankaj requested changes
Please fix all merge conflict issues that I commented on, and also use the automated code review feedback to fix your unused imports and other issues.

2017-07-22 20:12 UTC, tpankaj commented on visualizations/gradient_ascent.py
> +<<<<<<< HEAD
Fix merge conflict

2017-07-22 20:12 UTC, tpankaj commented on visualizations/gradient_ascent.py
> +<<<<<<< HEAD
Fix merge conflict

2017-07-24 00:37 UTC, tpankaj submitted a review, later dismissed
Please fix the Codacy errors before we merge.

2017-07-24 00:37 UTC, tpankaj commented on visualizations/gan_gradient_ascent.py
> +'''
Do you still need this commented stuff?

2017-07-24 00:37 UTC, tpankaj commented on visualizations/gan_gradient_ascent.py
> +            if save_timer.check():
Do you need this commented part?

2017-08-07 22:58 UTC, raunakdoesdev submitted a review, later dismissed
Looks good. I think we can merge this in.

2017-08-07 22:59 UTC, raunakdoesdev approved these changes
Looks good. I think we can merge this in.

2017-08-07 23:00 UTC, merged

2017-08-07 23:01 UTC, sauhaardac commented
Although this looks good I would like for the ARGS to be imported inside outside of a if __name__ == 'main'. Since sometimes for testing purposes we like to run the network test by itself using the unit test.I merged this now, since overall it looked good but it would be nice if we could do this in a future PR.